import authRouter from "../auth/auth.routes.js";
import deckRouter from "../deck/deck.routes.js";
import postRouter from "../post/post.routes.js";
import tagRouter from "../tag/tag.routes.js";
import mediaRouter from "../media/media.routes.js";
import testRouter from "../test/test.routes.js";
import itemRouter from "../item/item.routes.js";
import optionRouter from "../option/option.routes.js";
import sessionRouter from "../session/session.routes.js";
import userRouter from "../user/user.routes.js";
import attemptRouter from "../attempt/attempt.routes.js";
import courseRouter from "../course/course.routes.js";
import moduleRouter from "../module/module.routes.js";
import lessonRouter from "../lesson/lesson.routes.js";
import dashboardRouter from "../dashboard/dashboard.routes.js";
import { Router } from "express";

export const v1Router = Router();

v1Router.use("/auth", authRouter);
v1Router.use("/decks", deckRouter);
v1Router.use("/posts", postRouter);
v1Router.use("/tags", tagRouter);
v1Router.use("/media", mediaRouter);
v1Router.use("/tests", testRouter);
v1Router.use("/items", itemRouter);
v1Router.use("/options", optionRouter);
v1Router.use("/sessions", sessionRouter);
v1Router.use("/users", userRouter);
v1Router.use("/attempts", attemptRouter);
v1Router.use("/courses", courseRouter);
v1Router.use("/modules", moduleRouter);
v1Router.use("/lessons", lessonRouter);
v1Router.use("/dashboard", dashboardRouter);
